<?php
require_once get_stylesheet_directory() . '/inc/mega-menu-tutorials.php';

function syntaxsidekick_child_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('custom-logo', array(
        'height' => 180,
        'width' => 600,
        'flex-height' => true,
        'flex-width' => true,
    ));

    register_nav_menus(array(
        'primary' => __('Primary Menu', 'syntaxsidekick-child'),
        'footer' => __('Footer Menu', 'syntaxsidekick-child'),
    ));
}
add_action('after_setup_theme', 'syntaxsidekick_child_setup');

/**
 * Return file-based asset version when possible.
 *
 * @param string $relative_path Path relative to child theme root.
 *
 * @return string
 */
function syntaxsidekick_get_asset_version($relative_path) {
    $relative_path = ltrim((string) $relative_path, '/');
    $asset_path = trailingslashit(get_stylesheet_directory()) . $relative_path;
    $deploy_id = syntaxsidekick_get_deploy_id();

    if (file_exists($asset_path)) {
        return (string) filemtime($asset_path) . '-' . $deploy_id;
    }

    return (string) wp_get_theme()->get('Version') . '-' . $deploy_id;
}

/**
 * Read deployment identifier generated by CI to support cache busting and verification.
 *
 * @return string
 */
function syntaxsidekick_get_deploy_id() {
    static $deploy_id = null;

    if (null !== $deploy_id) {
        return $deploy_id;
    }

    $deploy_id = substr((string) wp_get_theme()->get('Version'), 0, 12);

    $meta_path = trailingslashit(get_stylesheet_directory()) . 'assets/deploy-meta.json';
    if (! file_exists($meta_path)) {
        return $deploy_id;
    }

    $raw = file_get_contents($meta_path);
    if (false === $raw || '' === trim($raw)) {
        return $deploy_id;
    }

    $meta = json_decode($raw, true);
    if (! is_array($meta) || empty($meta['deploy_id'])) {
        return $deploy_id;
    }

    $clean_id = preg_replace('/[^a-zA-Z0-9._-]/', '', (string) $meta['deploy_id']);
    if (! empty($clean_id)) {
        $deploy_id = substr($clean_id, 0, 40);
    }

    return $deploy_id;
}

/**
 * Print deploy marker for live verification in CI.
 *
 * @return void
 */
function syntaxsidekick_print_deploy_marker() {
    if (is_admin()) {
        return;
    }

    echo "\n<!-- syntaxsidekick-deploy:" . esc_html(syntaxsidekick_get_deploy_id()) . " -->\n";
}
add_action('wp_footer', 'syntaxsidekick_print_deploy_marker', 9999);

/**
 * Return cache version for transient invalidation.
 *
 * @return int
 */
function syntaxsidekick_perf_cache_version() {
    $version = (int) get_option('syntaxsidekick_perf_cache_version', 1);
    return max(1, $version);
}

/**
 * Bump performance cache version when content changes.
 *
 * @return void
 */
function syntaxsidekick_bump_perf_cache_version() {
    update_option('syntaxsidekick_perf_cache_version', syntaxsidekick_perf_cache_version() + 1, false);
}

add_action('save_post', 'syntaxsidekick_bump_perf_cache_version');
add_action('deleted_post', 'syntaxsidekick_bump_perf_cache_version');
add_action('set_object_terms', 'syntaxsidekick_bump_perf_cache_version');
add_action('created_category', 'syntaxsidekick_bump_perf_cache_version');
add_action('edited_category', 'syntaxsidekick_bump_perf_cache_version');
add_action('delete_category', 'syntaxsidekick_bump_perf_cache_version');
add_action('created_post_tag', 'syntaxsidekick_bump_perf_cache_version');
add_action('edited_post_tag', 'syntaxsidekick_bump_perf_cache_version');
add_action('delete_post_tag', 'syntaxsidekick_bump_perf_cache_version');

function syntaxsidekick_child_dequeue_parent_assets() {
    // The child theme provides its own full stylesheet and navigation script.
    wp_dequeue_style('syntax-sidekick-style');
    wp_deregister_style('syntax-sidekick-style');

    wp_dequeue_script('syntax-sidekick-navigation');
    wp_deregister_script('syntax-sidekick-navigation');
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_child_dequeue_parent_assets', 20);

function syntaxsidekick_child_enqueue_assets() {
    wp_enqueue_style(
        'syntaxsidekick-child-style',
        get_stylesheet_uri(),
        array(),
        syntaxsidekick_get_asset_version('style.css')
    );

    wp_enqueue_style(
        'syntaxsidekick-app',
        get_stylesheet_directory_uri() . '/assets/css/app.css',
        array('syntaxsidekick-child-style'),
        syntaxsidekick_get_asset_version('assets/css/app.css')
    );

    $nav_script_ver = syntaxsidekick_get_asset_version('assets/js/mega-menu.js');

    wp_enqueue_script(
        'syntaxsidekick-mega-menu',
        get_stylesheet_directory_uri() . '/assets/js/mega-menu.js',
        array(),
        $nav_script_ver,
        true
    );
    wp_script_add_data('syntaxsidekick-mega-menu', 'strategy', 'defer');

    wp_enqueue_script(
        'syntaxsidekick-theme-toggle',
        get_stylesheet_directory_uri() . '/assets/js/theme-toggle.js',
        array(),
        syntaxsidekick_get_asset_version('assets/js/theme-toggle.js'),
        true
    );
    wp_script_add_data('syntaxsidekick-theme-toggle', 'strategy', 'defer');

    if (is_front_page() || is_home()) {
        wp_enqueue_script(
            'syntaxsidekick-developer-bulletin',
            get_stylesheet_directory_uri() . '/assets/js/developer-bulletin.js',
            array(),
            syntaxsidekick_get_asset_version('assets/js/developer-bulletin.js'),
            true
        );
        wp_script_add_data('syntaxsidekick-developer-bulletin', 'strategy', 'defer');
    }

    if (function_exists('syntaxsidekick_get_mega_menu_js_payload')) {
        $payload = syntaxsidekick_get_mega_menu_js_payload();
        if (is_array($payload)) {
            wp_add_inline_script(
                'syntaxsidekick-mega-menu',
                'window.syntaxsidekickMegaMenuData = ' . wp_json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';',
                'before'
            );
        }
    }
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_child_enqueue_assets', 30);

/**
 * Enqueue responsive TOC relocation logic on single content layouts.
 *
 * @return void
 */
function syntaxsidekick_enqueue_toc_responsive() {
    $supported_types = array('post');

    foreach (array('guide', 'tutorial', 'resource') as $candidate_type) {
        if (post_type_exists($candidate_type)) {
            $supported_types[] = $candidate_type;
        }
    }

    if (! is_singular($supported_types)) {
        return;
    }

    wp_enqueue_script(
        'syntaxsidekick-toc-responsive',
        get_stylesheet_directory_uri() . '/assets/js/toc-responsive.js',
        array(),
        syntaxsidekick_get_asset_version('assets/js/toc-responsive.js'),
        true
    );
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_enqueue_toc_responsive', 35);

/**
 * Detect whether current singular content uses block markup.
 *
 * @return bool
 */
function syntaxsidekick_current_view_uses_blocks() {
    if (! is_singular()) {
        return false;
    }

    $object = get_queried_object();
    if (! ($object instanceof WP_Post)) {
        return false;
    }

    return has_blocks((string) $object->post_content);
}

/**
 * Dequeue non-essential global assets where we provide custom equivalents.
 *
 * @return void
 */
function syntaxsidekick_optimize_frontend_assets() {
    if (is_admin()) {
        return;
    }

    wp_dequeue_script('wp-embed');
    wp_deregister_script('wp-embed');

    if (is_user_logged_in() || is_customize_preview() || syntaxsidekick_current_view_uses_blocks()) {
        return;
    }

    wp_dequeue_style('wp-block-library');
    wp_dequeue_style('wp-block-library-theme');
    wp_dequeue_style('classic-theme-styles');
    wp_dequeue_style('global-styles');
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_optimize_frontend_assets', 100);

/**
 * Remove dashicons for anonymous visitors.
 *
 * @return void
 */
function syntaxsidekick_dequeue_dashicons_for_guests() {
    if (is_admin() || is_user_logged_in()) {
        return;
    }

    wp_dequeue_style('dashicons');
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_dequeue_dashicons_for_guests', 100);

/**
 * Restrict Easy TOC frontend assets to singular post pages.
 *
 * @return bool
 */
function syntaxsidekick_should_load_eztoc_assets() {
    return ! is_admin() && is_singular('post');
}

/**
 * Execute Easy TOC enqueue callbacks only when TOC is expected.
 *
 * @return void
 */
function syntaxsidekick_enqueue_eztoc_conditionally() {
    if (! syntaxsidekick_should_load_eztoc_assets() || ! class_exists('ezTOC')) {
        return;
    }

    ezTOC::enqueue_scripts();
    ezTOC::ez_toc_inline_styles();
    ezTOC::ez_toc_inline_sticky_styles();
    ezTOC::enqueue_scripts_for_exclude_css();
}

/**
 * Print Easy TOC schema only on supported single posts.
 *
 * @return void
 */
function syntaxsidekick_eztoc_schema_conditionally() {
    if (! syntaxsidekick_should_load_eztoc_assets() || ! class_exists('ezTOC')) {
        return;
    }

    ezTOC::ez_toc_schema_sitenav_creator();
}

/**
 * Rewire Easy TOC frontend hooks so they run only where needed.
 *
 * @return void
 */
function syntaxsidekick_optimize_toc_assets() {
    if (! class_exists('ezTOC')) {
        return;
    }

    remove_action('wp_enqueue_scripts', array('ezTOC', 'enqueue_scripts'));
    remove_action('wp_enqueue_scripts', array('ezTOC', 'ez_toc_inline_styles'));
    remove_action('wp_enqueue_scripts', array('ezTOC', 'ez_toc_inline_sticky_styles'));
    remove_action('wp_enqueue_scripts', array('ezTOC', 'enqueue_scripts_for_exclude_css'));
    remove_action('wp_head', array('ezTOC', 'ez_toc_schema_sitenav_creator'));

    add_action('wp_enqueue_scripts', 'syntaxsidekick_enqueue_eztoc_conditionally', 11);
    add_action('wp_head', 'syntaxsidekick_eztoc_schema_conditionally', 11);
}
add_action('init', 'syntaxsidekick_optimize_toc_assets', 20);

/**
 * Disable front-end assets/features we do not use.
 *
 * @return void
 */
function syntaxsidekick_optimize_frontend_bootstrap() {
    if (is_admin()) {
        return;
    }

    remove_action('wp_head', 'print_emoji_detection_script', 7);
    remove_action('wp_print_styles', 'print_emoji_styles');
    remove_action('wp_head', 'wp_oembed_add_discovery_links');
    remove_action('wp_head', 'wp_oembed_add_host_js');
    wp_dequeue_script('wp-embed');
}
add_action('init', 'syntaxsidekick_optimize_frontend_bootstrap');

/**
 * Apply lightweight iframe defaults for performance and accessibility.
 *
 * @param string $content Post content HTML.
 *
 * @return string
 */
function syntaxsidekick_optimize_content_iframes($content) {
    if (is_admin() || ! is_string($content) || '' === trim($content) || false === stripos($content, '<iframe')) {
        return $content;
    }

    if (! class_exists('DOMDocument')) {
        return $content;
    }

    $internal_errors = libxml_use_internal_errors(true);
    $document = new DOMDocument('1.0', 'UTF-8');
    $html = '<div id="ss-iframe-opt-root">' . mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8') . '</div>';

    if (! $document->loadHTML('<?xml encoding="utf-8" ?>' . $html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD)) {
        libxml_clear_errors();
        libxml_use_internal_errors($internal_errors);
        return $content;
    }

    $iframes = $document->getElementsByTagName('iframe');
    foreach ($iframes as $iframe) {
        if (! $iframe instanceof DOMElement) {
            continue;
        }

        if (! $iframe->hasAttribute('loading')) {
            $iframe->setAttribute('loading', 'lazy');
        }

        if (! $iframe->hasAttribute('referrerpolicy')) {
            $iframe->setAttribute('referrerpolicy', 'strict-origin-when-cross-origin');
        }

        if (! $iframe->hasAttribute('title')) {
            $iframe->setAttribute('title', __('Embedded content', 'syntaxsidekick-child'));
        }
    }

    $root = $document->getElementById('ss-iframe-opt-root');
    $output = '';
    if ($root instanceof DOMElement) {
        foreach ($root->childNodes as $child_node) {
            $output .= $document->saveHTML($child_node);
        }
    }

    libxml_clear_errors();
    libxml_use_internal_errors($internal_errors);

    return '' !== $output ? $output : $content;
}
add_filter('the_content', 'syntaxsidekick_optimize_content_iframes', 12);

/**
 * Apply persisted theme preference before first paint.
 *
 * @return void
 */
function syntaxsidekick_output_theme_bootstrap_script() {
    if (is_admin()) {
        return;
    }

    echo "<script>(function(){try{var d=document.documentElement;var k='syntaxsidekick-theme';var l='ss-theme';var t=localStorage.getItem(k);if(t!=='dark'&&t!=='light'){var legacy=localStorage.getItem(l);if(legacy==='dark'||legacy==='light'){t=legacy;localStorage.setItem(k,legacy);}else{t=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}}d.setAttribute('data-theme',t);}catch(e){if(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches){document.documentElement.setAttribute('data-theme','dark');}else{document.documentElement.setAttribute('data-theme','light');}}})();</script>\n";
}
add_action('wp_head', 'syntaxsidekick_output_theme_bootstrap_script', 1);

/**
 * Remove jQuery Migrate from frontend payload while keeping jQuery.
 *
 * @param WP_Scripts $scripts Scripts registry.
 *
 * @return void
 */
function syntaxsidekick_remove_jquery_migrate($scripts) {
    if (is_admin() || ! ($scripts instanceof WP_Scripts)) {
        return;
    }

    if (! isset($scripts->registered['jquery']) || ! is_array($scripts->registered['jquery']->deps)) {
        return;
    }

    $scripts->registered['jquery']->deps = array_values(
        array_diff($scripts->registered['jquery']->deps, array('jquery-migrate'))
    );
}
add_action('wp_default_scripts', 'syntaxsidekick_remove_jquery_migrate');

function syntaxsidekick_excerpt_length($length) {
    return 22;
}
add_filter('excerpt_length', 'syntaxsidekick_excerpt_length');

function syntaxsidekick_excerpt_more($more) {
    return '...';
}
add_filter('excerpt_more', 'syntaxsidekick_excerpt_more');

/**
 * Return local SVG icon markup by name.
 *
 * @param string $icon_name Icon filename without extension.
 * @param array  $args      Optional render args.
 *
 * @return string
 */
function syntaxsidekick_icon($icon_name, $args = array()) {
    static $raw_cache = array();

    $icon_name = sanitize_key((string) $icon_name);
    if ('' === $icon_name) {
        return '';
    }

    if (! array_key_exists($icon_name, $raw_cache)) {
        $icons_dir = trailingslashit(get_stylesheet_directory()) . 'assets/icons/';
        $path = $icons_dir . $icon_name . '.svg';

        if (! file_exists($path) || ! is_readable($path)) {
            $raw_cache[$icon_name] = '';
        } else {
            $raw = file_get_contents($path);
            if (false === $raw || '' === trim($raw)) {
                $raw_cache[$icon_name] = '';
            } else {
                $raw = preg_replace('/<\?xml[^>]*>\s*/i', '', $raw);
                $raw = is_string($raw) ? preg_replace('/<title>.*?<\/title>/is', '', $raw) : '';
                $raw = is_string($raw) ? trim($raw) : '';
                $raw_cache[$icon_name] = $raw;
            }
        }
    }

    $svg = $raw_cache[$icon_name];
    if (! is_string($svg) || '' === $svg) {
        return '';
    }

    $defaults = array(
        'class' => 'ss-menu-icon ss-icon--neutral',
        'decorative' => true,
        'title' => '',
        'label' => '',
    );

    $args = wp_parse_args(is_array($args) ? $args : array(), $defaults);
    $class_attr = trim((string) $args['class']);
    $decorative = (bool) $args['decorative'];
    $title = trim((string) $args['title']);
    $label = trim((string) $args['label']);

    if (false === stripos($svg, 'viewBox=')) {
        $svg = preg_replace('/<svg\b/i', '<svg viewBox="0 0 24 24"', $svg, 1);
        if (! is_string($svg)) {
            return '';
        }
    }

    $attrs = array();
    if ('' !== $class_attr) {
        $attrs[] = 'class="' . esc_attr($class_attr) . '"';
    }

    if ($decorative) {
        $attrs[] = 'aria-hidden="true"';
        $attrs[] = 'focusable="false"';
    } else {
        $attrs[] = 'role="img"';

        if ('' !== $label) {
            $attrs[] = 'aria-label="' . esc_attr($label) . '"';
        }

        if ('' !== $title && '' === $label) {
            $attrs[] = 'aria-label="' . esc_attr($title) . '"';
        }
    }

    $svg = preg_replace('/<svg\b([^>]*)>/i', '<svg$1 ' . implode(' ', $attrs) . '>', $svg, 1);
    if (! is_string($svg) || '' === trim($svg)) {
        return '';
    }

    if (! $decorative && '' !== $title) {
        $svg = preg_replace('/<svg\b[^>]*>/i', '$0<title>' . esc_html($title) . '</title>', $svg, 1);
        if (! is_string($svg)) {
            return '';
        }
    }

    return $svg;
}

/**
 * Get semantic icon color utility class by slug.
 *
 * @param string $slug Icon/topic slug.
 *
 * @return string
 */
function syntaxsidekick_get_icon_color_class($slug) {
    $slug = sanitize_key((string) $slug);

    $map = array(
        'html' => 'ss-icon--html5',
        'html5' => 'ss-icon--html5',
        'css' => 'ss-icon--css',
        'javascript' => 'ss-icon--javascript',
        'js' => 'ss-icon--javascript',
        'typescript' => 'ss-icon--typescript',
        'ts' => 'ss-icon--typescript',
        'react' => 'ss-icon--react',
        'vue' => 'ss-icon--vue',
        'vuejs' => 'ss-icon--vue',
        'wordpress' => 'ss-icon--wordpress',
        'accessibility' => 'ss-icon--accessibility',
        'performance' => 'ss-icon--performance',
    );

    return $map[$slug] ?? 'ss-icon--neutral';
}

function syntaxsidekick_fallback_menu($args = array()) {
    $menu_class = ! empty($args['menu_class']) ? (string) $args['menu_class'] : 'ss-nav-list ss-nav-list--fallback';

    $links = array(
        array(
            'label' => 'Home',
            'url' => home_url('/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('home'),
        ),
        array(
            'label' => 'Articles',
            'url' => home_url('/articles/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('articles'),
        ),
        array(
            'label' => 'Tutorials',
            'url' => home_url('/tutorials/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('tutorials'),
        ),
        array(
            'label' => 'Guides',
            'url' => home_url('/guides/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('guides'),
        ),
        array(
            'label' => 'Resources',
            'url' => home_url('/resources/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('resources'),
        ),
        array(
            'label' => 'About',
            'url' => home_url('/about/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('about'),
        ),
        array(
            'label' => 'Contact',
            'url' => home_url('/contact/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('contact'),
        ),
    );

    echo '<ul class="' . esc_attr($menu_class) . '" role="list">';

    foreach ($links as $link) {
        $item_classes = 'ss-nav-item';
        $link_classes = 'ss-nav-link';
        $section_key = syntaxsidekick_nav_section_from_url($link['url']);
        $data_key_attr = '' !== $section_key ? ' data-ss-menu-key="' . esc_attr($section_key) . '"' : '';

        if ($link['active']) {
            $item_classes .= ' current-menu-item is-active';
            $link_classes .= ' is-active';
        }

        echo '<li class="' . esc_attr($item_classes) . '"><a class="' . esc_attr($link_classes) . '" href="' . esc_url($link['url']) . '"' . $data_key_attr . '>' . esc_html($link['label']) . '</a></li>';
    }

    echo '</ul>';
}

/**
 * Normalize request path relative to site home path.
 *
 * @return string
 */
function syntaxsidekick_get_relative_request_path() {
    $request_uri = isset($_SERVER['REQUEST_URI']) ? wp_unslash((string) $_SERVER['REQUEST_URI']) : '/';
    $request_path = wp_parse_url($request_uri, PHP_URL_PATH);
    $request_path = is_string($request_path) && '' !== $request_path ? $request_path : '/';

    $home_path = wp_parse_url(home_url('/'), PHP_URL_PATH);
    $home_path = is_string($home_path) && '' !== $home_path ? $home_path : '/';

    $request_path = '/' . ltrim($request_path, '/');

    if ('/' !== $home_path) {
        $trimmed_home = rtrim($home_path, '/');
        if ($request_path === $trimmed_home) {
            $request_path = '/';
        } elseif (0 === strpos($request_path, $trimmed_home . '/')) {
            $request_path = substr($request_path, strlen($trimmed_home));
            $request_path = '' === $request_path ? '/' : $request_path;
        }
    }

    if ('/' !== $request_path && '/' !== substr($request_path, -1)) {
        $request_path .= '/';
    }

    return $request_path;
}

/**
 * Map navigation URL to its section key.
 *
 * @param string $url Menu URL.
 *
 * @return string
 */
function syntaxsidekick_nav_section_from_url($url) {
    $path = wp_parse_url((string) $url, PHP_URL_PATH);
    $path = is_string($path) && '' !== $path ? $path : '/';

    $home_path = wp_parse_url(home_url('/'), PHP_URL_PATH);
    $home_path = is_string($home_path) && '' !== $home_path ? $home_path : '/';

    $path = '/' . ltrim($path, '/');

    if ('/' !== $home_path) {
        $trimmed_home = rtrim($home_path, '/');
        if ($path === $trimmed_home) {
            $path = '/';
        } elseif (0 === strpos($path, $trimmed_home . '/')) {
            $path = substr($path, strlen($trimmed_home));
            $path = '' === $path ? '/' : $path;
        }
    }

    if ('/' !== $path && '/' !== substr($path, -1)) {
        $path .= '/';
    }

    $section_map = array(
        '/' => 'home',
        '/articles/' => 'articles',
        '/tutorials/' => 'tutorials',
        '/guides/' => 'guides',
        '/resources/' => 'resources',
        '/about/' => 'about',
        '/contact/' => 'contact',
    );

    return isset($section_map[$path]) ? $section_map[$path] : '';
}

function syntaxsidekick_primary_nav_item_classes($classes, $menu_item, $args) {
    if (empty($args->theme_location) || 'primary' !== $args->theme_location) {
        return $classes;
    }

    $classes[] = 'ss-nav-item';

    $section_key = syntaxsidekick_nav_section_from_url(isset($menu_item->url) ? (string) $menu_item->url : '');

    $classes = array_values(
        array_filter(
            $classes,
            static function ($class_name) {
                return ! in_array($class_name, array('is-active', 'current-menu-item', 'current-menu-parent', 'current-menu-ancestor'), true);
            }
        )
    );

    if ('' !== $section_key && syntaxsidekick_is_mega_menu_section_active($section_key)) {
        $classes[] = 'is-active';
        $classes[] = 'current-menu-item';
    }

    return array_values(array_unique($classes));
}
add_filter('nav_menu_css_class', 'syntaxsidekick_primary_nav_item_classes', 10, 3);

function syntaxsidekick_primary_nav_link_attributes($atts, $menu_item, $args) {
    if (empty($args->theme_location) || 'primary' !== $args->theme_location) {
        return $atts;
    }

    $classes   = isset($atts['class']) ? (string) $atts['class'] : '';
    $class_arr = preg_split('/\s+/', trim($classes));
    $class_arr = is_array($class_arr) ? array_filter($class_arr) : array();
    $class_arr[] = 'ss-nav-link';

    $section_key = syntaxsidekick_nav_section_from_url(isset($menu_item->url) ? (string) $menu_item->url : '');
    if ('' !== $section_key && syntaxsidekick_is_mega_menu_section_active($section_key)) {
        $class_arr[] = 'is-active';
    }

    if ('' !== $section_key) {
        $atts['data-ss-menu-key'] = $section_key;
    }

    $atts['class'] = implode(' ', array_values(array_unique($class_arr)));

    return $atts;
}
add_filter('nav_menu_link_attributes', 'syntaxsidekick_primary_nav_link_attributes', 10, 3);

function syntaxsidekick_has_seo_plugin() {
    return defined('RANK_MATH_VERSION') || defined('WPSEO_VERSION') || defined('AIOSEO_VERSION') || defined('SEOPRESS_VERSION');
}

function syntaxsidekick_fallback_meta_description() {
    if (is_front_page() || is_home()) {
        return get_bloginfo('description');
    }

    if (is_singular()) {
        $description = trim((string) get_the_excerpt());
        if ('' === $description) {
            $description = wp_strip_all_tags((string) get_the_content());
        }

        return wp_trim_words($description, 28, '...');
    }

    if (is_archive()) {
        $description = trim((string) get_the_archive_description());
        if ('' !== $description) {
            return wp_strip_all_tags($description);
        }
    }

    return get_bloginfo('description');
}

function syntaxsidekick_output_fallback_seo_meta() {
    if (syntaxsidekick_has_seo_plugin()) {
        return;
    }

    $description = syntaxsidekick_fallback_meta_description();
    if ('' !== $description) {
        echo '<meta name="description" content="' . esc_attr($description) . '">' . "\n";
    }

    $canonical = wp_get_canonical_url();
    if (! $canonical) {
        $canonical = is_home() ? home_url('/') : get_permalink();
    }

    if ($canonical) {
        echo '<link rel="canonical" href="' . esc_url($canonical) . '">' . "\n";
    }

    if (is_single()) {
        $schema = array(
            '@context' => 'https://schema.org',
            '@type' => 'Article',
            'headline' => get_the_title(),
            'datePublished' => get_the_date('c'),
            'dateModified' => get_the_modified_date('c'),
            'author' => array(
                '@type' => 'Person',
                'name' => get_the_author(),
            ),
            'mainEntityOfPage' => array(
                '@type' => 'WebPage',
                '@id' => get_permalink(),
            ),
        );

        if (has_post_thumbnail()) {
            $image_url = get_the_post_thumbnail_url(null, 'large');
            if ($image_url) {
                $schema['image'] = array($image_url);
            }
        }

        echo '<script type="application/ld+json">' . wp_json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>' . "\n";
    }
}
add_action('wp_head', 'syntaxsidekick_output_fallback_seo_meta', 5);

function syntaxsidekick_get_post_read_time($post_id) {
    $post_id = (int) $post_id;
    if ($post_id <= 0) {
        return '1 min read';
    }

    $word_count = str_word_count(wp_strip_all_tags((string) get_post_field('post_content', $post_id)));
    $minutes    = max(1, (int) ceil($word_count / 200));

    return $minutes . ' min read';
}

function syntaxsidekick_get_home_feature_highlights() {
    return array(
        array(
            'icon' => '</>',
            'title' => 'Modern Standards',
            'description' => 'CSS, JS, TS and beyond',
        ),
        array(
            'icon' => 'A11y',
            'title' => 'Accessibility First',
            'description' => 'Inclusive by default',
        ),
        array(
            'icon' => 'Perf',
            'title' => 'Performance Focused',
            'description' => 'Fast by design',
        ),
        array(
            'icon' => 'Idea',
            'title' => 'Practical Learning',
            'description' => 'Real world examples',
        ),
    );
}

function syntaxsidekick_get_twitch_channel_url() {
    return 'https://www.twitch.tv/syntaxsidekick';
}

function syntaxsidekick_get_twitch_credentials() {
    $client_id     = defined('TWITCH_CLIENT_ID') ? sanitize_text_field((string) TWITCH_CLIENT_ID) : '';
    $client_secret = defined('TWITCH_CLIENT_SECRET') ? (string) TWITCH_CLIENT_SECRET : '';

    if ('' === $client_id || '' === $client_secret) {
        return null;
    }

    return array(
        'client_id' => $client_id,
        'client_secret' => $client_secret,
    );
}

function syntaxsidekick_get_twitch_fallback_data($reason = '') {
    $description = 'Catch SyntaxSidekick streams, tutorials, and replays on Twitch.';

    if ('missing_credentials' === $reason) {
        $description = 'Twitch stream status is unavailable until API credentials are configured.';
    }

    return array(
        'state' => 'fallback',
        'title' => 'SyntaxSidekick on Twitch',
        'description' => $description,
        'platform' => 'Twitch',
        'cta_label' => 'Visit SyntaxSidekick on Twitch',
        'cta_url' => syntaxsidekick_get_twitch_channel_url(),
    );
}

function syntaxsidekick_get_twitch_access_token() {
    $cached = get_transient('syntaxsidekick_twitch_access_token');
    if (is_string($cached) && '' !== $cached) {
        return $cached;
    }

    $credentials = syntaxsidekick_get_twitch_credentials();
    if (null === $credentials) {
        return new WP_Error('syntaxsidekick_twitch_missing_credentials', 'Twitch credentials are missing.');
    }

    $response = wp_remote_post(
        'https://id.twitch.tv/oauth2/token',
        array(
            'timeout' => 8,
            'body' => array(
                'client_id' => $credentials['client_id'],
                'client_secret' => $credentials['client_secret'],
                'grant_type' => 'client_credentials',
            ),
        )
    );

    if (is_wp_error($response)) {
        return $response;
    }

    $status = (int) wp_remote_retrieve_response_code($response);
    $body   = json_decode((string) wp_remote_retrieve_body($response), true);

    if (200 !== $status || ! is_array($body) || empty($body['access_token'])) {
        return new WP_Error('syntaxsidekick_twitch_token_error', 'Unable to retrieve Twitch access token.');
    }

    $token      = sanitize_text_field((string) $body['access_token']);
    $expires_in = isset($body['expires_in']) ? max(300, (int) $body['expires_in'] - 300) : HOUR_IN_SECONDS;

    set_transient('syntaxsidekick_twitch_access_token', $token, $expires_in);

    return $token;
}

function syntaxsidekick_twitch_api_get($endpoint, $query = array()) {
    $credentials = syntaxsidekick_get_twitch_credentials();
    if (null === $credentials) {
        return new WP_Error('syntaxsidekick_twitch_missing_credentials', 'Twitch credentials are missing.');
    }

    $token = syntaxsidekick_get_twitch_access_token();
    if (is_wp_error($token)) {
        return $token;
    }

    $url = add_query_arg($query, 'https://api.twitch.tv/helix/' . ltrim((string) $endpoint, '/'));

    $response = wp_remote_get(
        $url,
        array(
            'timeout' => 8,
            'headers' => array(
                'Authorization' => 'Bearer ' . $token,
                'Client-Id' => $credentials['client_id'],
            ),
        )
    );

    if (is_wp_error($response)) {
        return $response;
    }

    $status = (int) wp_remote_retrieve_response_code($response);
    $body   = json_decode((string) wp_remote_retrieve_body($response), true);

    if (200 !== $status || ! is_array($body)) {
        return new WP_Error('syntaxsidekick_twitch_api_error', 'Unable to retrieve Twitch API data.');
    }

    return $body;
}

function syntaxsidekick_get_twitch_broadcaster_id() {
    $channel = 'syntaxsidekick';
    $cached  = get_transient('syntaxsidekick_twitch_broadcaster_id_' . $channel);

    if (is_string($cached) && '' !== $cached) {
        return $cached;
    }

    $body = syntaxsidekick_twitch_api_get('users', array('login' => $channel));
    if (is_wp_error($body) || empty($body['data'][0]['id'])) {
        return is_wp_error($body) ? $body : new WP_Error('syntaxsidekick_twitch_user_missing', 'Twitch broadcaster was not found.');
    }

    $broadcaster_id = sanitize_text_field((string) $body['data'][0]['id']);
    set_transient('syntaxsidekick_twitch_broadcaster_id_' . $channel, $broadcaster_id, DAY_IN_SECONDS);

    return $broadcaster_id;
}

function syntaxsidekick_get_twitch_stream_status() {
    $channel = 'syntaxsidekick';
    $cached  = get_transient('syntaxsidekick_twitch_stream_status_' . $channel);

    if (is_array($cached)) {
        return $cached;
    }

    $body = syntaxsidekick_twitch_api_get('streams', array('user_login' => $channel));
    if (is_wp_error($body)) {
        return $body;
    }

    $stream = ! empty($body['data'][0]) && is_array($body['data'][0]) ? $body['data'][0] : array();
    $status = array(
        'is_live' => ! empty($stream),
        'title' => ! empty($stream['title']) ? sanitize_text_field((string) $stream['title']) : '',
        'game_name' => ! empty($stream['game_name']) ? sanitize_text_field((string) $stream['game_name']) : '',
    );

    set_transient('syntaxsidekick_twitch_stream_status_' . $channel, $status, 3 * MINUTE_IN_SECONDS);

    return $status;
}

function syntaxsidekick_get_twitch_latest_video($broadcaster_id) {
    $broadcaster_id = sanitize_text_field((string) $broadcaster_id);
    if ('' === $broadcaster_id) {
        return null;
    }

    $cached = get_transient('syntaxsidekick_twitch_latest_video_' . $broadcaster_id);
    if (is_array($cached)) {
        return $cached;
    }

    $body = syntaxsidekick_twitch_api_get(
        'videos',
        array(
            'user_id' => $broadcaster_id,
            'first' => 1,
            'type' => 'archive',
        )
    );

    if (is_wp_error($body)) {
        return $body;
    }

    $video = ! empty($body['data'][0]) && is_array($body['data'][0]) ? $body['data'][0] : array();
    if (empty($video['id'])) {
        set_transient('syntaxsidekick_twitch_latest_video_' . $broadcaster_id, array(), 15 * MINUTE_IN_SECONDS);
        return null;
    }

    $thumbnail = ! empty($video['thumbnail_url']) ? (string) $video['thumbnail_url'] : '';
    $thumbnail = str_replace(array('%{width}', '%{height}'), array('640', '360'), $thumbnail);

    $latest = array(
        'id' => sanitize_text_field((string) $video['id']),
        'title' => ! empty($video['title']) ? sanitize_text_field((string) $video['title']) : 'Latest Twitch stream',
        'url' => ! empty($video['url']) ? esc_url_raw((string) $video['url']) : syntaxsidekick_get_twitch_channel_url(),
        'duration' => ! empty($video['duration']) ? sanitize_text_field((string) $video['duration']) : '',
        'thumbnail' => esc_url_raw($thumbnail),
    );

    set_transient('syntaxsidekick_twitch_latest_video_' . $broadcaster_id, $latest, 15 * MINUTE_IN_SECONDS);

    return $latest;
}

function syntaxsidekick_get_live_video_data() {
    if (null === syntaxsidekick_get_twitch_credentials()) {
        return apply_filters('syntaxsidekick_live_video_data', syntaxsidekick_get_twitch_fallback_data('missing_credentials'));
    }

    $channel_url = syntaxsidekick_get_twitch_channel_url();
    $stream      = syntaxsidekick_get_twitch_stream_status();
    if (is_wp_error($stream)) {
        return apply_filters('syntaxsidekick_live_video_data', syntaxsidekick_get_twitch_fallback_data('api_error'));
    }

    if (! empty($stream['is_live'])) {
        $stream_title = ! empty($stream['title']) ? $stream['title'] : 'SyntaxSidekick is live on Twitch';
        $game_name    = ! empty($stream['game_name']) ? ' Streaming ' . $stream['game_name'] . '.' : '';

        return apply_filters(
            'syntaxsidekick_live_video_data',
            array(
                'state' => 'live',
                'title' => $stream_title,
                'description' => 'SyntaxSidekick is live now on Twitch.' . $game_name,
                'platform' => 'Twitch live stream',
                'cta_label' => 'Live Now',
                'cta_url' => $channel_url,
                'embed_src' => 'https://player.twitch.tv/?channel=syntaxsidekick&muted=true',
                'embed_title' => 'SyntaxSidekick live Twitch stream',
            )
        );
    }

    $broadcaster_id = syntaxsidekick_get_twitch_broadcaster_id();
    if (is_wp_error($broadcaster_id)) {
        return apply_filters('syntaxsidekick_live_video_data', syntaxsidekick_get_twitch_fallback_data('api_error'));
    }

    $latest_video = syntaxsidekick_get_twitch_latest_video($broadcaster_id);
    if (is_wp_error($latest_video)) {
        return apply_filters('syntaxsidekick_live_video_data', syntaxsidekick_get_twitch_fallback_data('api_error'));
    }

    if (is_array($latest_video) && ! empty($latest_video['id'])) {
        return apply_filters(
            'syntaxsidekick_live_video_data',
            array(
                'state' => 'offline',
                'title' => $latest_video['title'],
                'description' => 'SyntaxSidekick is offline right now. Watch the latest Twitch stream replay.',
                'platform' => 'Latest Twitch video',
                'cta_label' => 'Watch Latest Stream',
                'cta_url' => $latest_video['url'],
                'embed_src' => 'https://player.twitch.tv/?video=' . rawurlencode($latest_video['id']) . '&muted=true',
                'embed_title' => 'Latest SyntaxSidekick Twitch video',
                'latest_title' => $latest_video['title'],
                'latest_url' => $latest_video['url'],
                'latest_duration' => $latest_video['duration'],
                'latest_thumbnail' => $latest_video['thumbnail'],
                'latest_thumbnail_alt' => 'Latest SyntaxSidekick Twitch video thumbnail',
            )
        );
    }

    $default = array(
        'state' => 'offline',
        'title' => 'SyntaxSidekick on Twitch',
        'description' => 'SyntaxSidekick is offline right now. Visit Twitch for streams and replays.',
        'platform' => 'Twitch',
        'cta_label' => 'Visit SyntaxSidekick on Twitch',
        'cta_url' => $channel_url,
    );

    return apply_filters('syntaxsidekick_live_video_data', $default);
}

/**
 * Return the dedicated News Bulletins category term when available.
 *
 * @return WP_Term|null
 */
function syntaxsidekick_get_news_bulletins_term() {
    $candidates = array(
        array('field' => 'slug', 'value' => 'news-bulletins'),
        array('field' => 'slug', 'value' => 'news-bulletin'),
        array('field' => 'name', 'value' => 'News Bulletins'),
        array('field' => 'name', 'value' => 'News Bulletin'),
    );

    $term = null;
    foreach ($candidates as $candidate) {
        $candidate_term = get_term_by($candidate['field'], $candidate['value'], 'category');
        if ($candidate_term instanceof WP_Term) {
            $term = $candidate_term;
            break;
        }
    }

    if (! ($term instanceof WP_Term)) {
        return null;
    }

    return $term;
}

/**
 * Resolve bulletin accent variant from category and tag metadata.
 *
 * @param int $post_id Post ID.
 * @param int $news_bulletins_term_id Dedicated category ID.
 *
 * @return string
 */
function syntaxsidekick_get_bulletin_accent_variant($post_id, $news_bulletins_term_id = 0) {
    $post_id = (int) $post_id;

    if ($post_id <= 0) {
        return 'green';
    }

    $variant_keywords = array(
        'green' => array('general-announcement', 'soft-launch', 'feature-release'),
        'blue' => array('new-guide', 'new-tutorial'),
        'yellow' => array('live-stream', 'upcoming-event'),
        'purple' => array('new-resource'),
        'red' => array('scheduled-maintenance', 'known-issue'),
    );

    $terms = wp_get_post_terms($post_id, array('category', 'post_tag'));
    if (is_wp_error($terms) || empty($terms)) {
        return 'green';
    }

    foreach ($terms as $term) {
        if (! ($term instanceof WP_Term)) {
            continue;
        }

        if (
            (int) $news_bulletins_term_id > 0
            && 'category' === $term->taxonomy
            && (int) $term->term_id === (int) $news_bulletins_term_id
        ) {
            continue;
        }

        $needle = strtolower(trim($term->slug . ' ' . $term->name));

        foreach ($variant_keywords as $variant => $keywords) {
            foreach ($keywords as $keyword) {
                if (false !== strpos($needle, $keyword)) {
                    return $variant;
                }
            }
        }
    }

    return 'green';
}

/**
 * Resolve bulletin CTA URL and label from custom fields with fallbacks.
 *
 * @param int    $post_id Bulletin post ID.
 * @param string $slot CTA slot name.
 * @param string $fallback_label Fallback label.
 * @param string $fallback_url Fallback URL.
 *
 * @return array{label:string,url:string}
 */
function syntaxsidekick_get_bulletin_cta($post_id, $slot, $fallback_label, $fallback_url) {
    $post_id = (int) $post_id;
    $slot = sanitize_key((string) $slot);

    $label = (string) $fallback_label;
    $url = (string) $fallback_url;

    $link_fields = array(
        'bulletin_' . $slot . '_cta',
        $slot . '_cta',
        'bulletin_' . $slot . '_button',
    );

    if (function_exists('get_field')) {
        foreach ($link_fields as $field_key) {
            $field_value = get_field($field_key, $post_id);

            if (is_array($field_value)) {
                if (! empty($field_value['title'])) {
                    $label = (string) $field_value['title'];
                }

                if (! empty($field_value['url'])) {
                    $url = (string) $field_value['url'];
                }
            } elseif (is_string($field_value) && '' !== trim($field_value) && wp_http_validate_url($field_value)) {
                $url = $field_value;
            }
        }
    }

    $label_meta_keys = array(
        'syntaxsidekick_bulletin_' . $slot . '_label',
        'bulletin_' . $slot . '_label',
        $slot . '_cta_label',
    );

    foreach ($label_meta_keys as $meta_key) {
        $meta_value = get_post_meta($post_id, $meta_key, true);

        if (is_string($meta_value) && '' !== trim($meta_value)) {
            $label = $meta_value;
            break;
        }
    }

    $url_meta_keys = array(
        'syntaxsidekick_bulletin_' . $slot . '_url',
        'bulletin_' . $slot . '_url',
        $slot . '_cta_url',
    );

    foreach ($url_meta_keys as $meta_key) {
        $meta_value = get_post_meta($post_id, $meta_key, true);

        if (is_string($meta_value) && '' !== trim($meta_value)) {
            $url = $meta_value;
            break;
        }
    }

    $label = trim(wp_strip_all_tags($label));
    if ('' === $label) {
        $label = (string) $fallback_label;
    }

    if ('' === trim($url)) {
        $url = (string) $fallback_url;
    }

    return array(
        'label' => $label,
        'url' => $url,
    );
}
