<?php
require_once get_stylesheet_directory() . '/inc/mega-menu-tutorials.php';

function syntaxsidekick_child_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('custom-logo', array(
        'height' => 180,
        'width' => 600,
        'flex-height' => true,
        'flex-width' => true,
    ));

    register_nav_menus(array(
        'primary' => __('Primary Menu', 'syntaxsidekick-child'),
        'footer' => __('Footer Menu', 'syntaxsidekick-child'),
    ));
}
add_action('after_setup_theme', 'syntaxsidekick_child_setup');

/**
 * Return file-based asset version when possible.
 *
 * @param string $relative_path Path relative to child theme root.
 *
 * @return string
 */
function syntaxsidekick_get_asset_version($relative_path) {
    $relative_path = ltrim((string) $relative_path, '/');
    $asset_path = trailingslashit(get_stylesheet_directory()) . $relative_path;
    $deploy_id = syntaxsidekick_get_deploy_id();

    if (file_exists($asset_path)) {
        return (string) filemtime($asset_path) . '-' . $deploy_id;
    }

    return (string) wp_get_theme()->get('Version') . '-' . $deploy_id;
}

/**
 * Read deployment identifier generated by CI to support cache busting and verification.
 *
 * @return string
 */
function syntaxsidekick_get_deploy_id() {
    static $deploy_id = null;

    if (null !== $deploy_id) {
        return $deploy_id;
    }

    $deploy_id = substr((string) wp_get_theme()->get('Version'), 0, 12);

    $meta_path = trailingslashit(get_stylesheet_directory()) . 'assets/deploy-meta.json';
    if (! file_exists($meta_path)) {
        return $deploy_id;
    }

    $raw = file_get_contents($meta_path);
    if (false === $raw || '' === trim($raw)) {
        return $deploy_id;
    }

    $meta = json_decode($raw, true);
    if (! is_array($meta) || empty($meta['deploy_id'])) {
        return $deploy_id;
    }

    $clean_id = preg_replace('/[^a-zA-Z0-9._-]/', '', (string) $meta['deploy_id']);
    if (! empty($clean_id)) {
        $deploy_id = substr($clean_id, 0, 40);
    }

    return $deploy_id;
}

/**
 * Print deploy marker for live verification in CI.
 *
 * @return void
 */
function syntaxsidekick_print_deploy_marker() {
    if (is_admin()) {
        return;
    }

    echo "\n<!-- syntaxsidekick-deploy:" . esc_html(syntaxsidekick_get_deploy_id()) . " -->\n";
}
add_action('wp_footer', 'syntaxsidekick_print_deploy_marker', 9999);

/**
 * Return cache version for transient invalidation.
 *
 * @return int
 */
function syntaxsidekick_perf_cache_version() {
    $version = (int) get_option('syntaxsidekick_perf_cache_version', 1);
    return max(1, $version);
}

/**
 * Bump performance cache version when content changes.
 *
 * @return void
 */
function syntaxsidekick_bump_perf_cache_version() {
    update_option('syntaxsidekick_perf_cache_version', syntaxsidekick_perf_cache_version() + 1, false);
}

add_action('save_post', 'syntaxsidekick_bump_perf_cache_version');
add_action('deleted_post', 'syntaxsidekick_bump_perf_cache_version');
add_action('set_object_terms', 'syntaxsidekick_bump_perf_cache_version');
add_action('created_category', 'syntaxsidekick_bump_perf_cache_version');
add_action('edited_category', 'syntaxsidekick_bump_perf_cache_version');
add_action('delete_category', 'syntaxsidekick_bump_perf_cache_version');
add_action('created_post_tag', 'syntaxsidekick_bump_perf_cache_version');
add_action('edited_post_tag', 'syntaxsidekick_bump_perf_cache_version');
add_action('delete_post_tag', 'syntaxsidekick_bump_perf_cache_version');

function syntaxsidekick_child_dequeue_parent_assets() {
    // The child theme provides its own full stylesheet and navigation script.
    wp_dequeue_style('syntax-sidekick-style');
    wp_deregister_style('syntax-sidekick-style');

    wp_dequeue_script('syntax-sidekick-navigation');
    wp_deregister_script('syntax-sidekick-navigation');
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_child_dequeue_parent_assets', 20);

function syntaxsidekick_child_enqueue_assets() {
    wp_enqueue_style(
        'syntaxsidekick-child-style',
        get_stylesheet_uri(),
        array(),
        syntaxsidekick_get_asset_version('style.css')
    );

    $global_css_modules = array(
        'assets/css/layers.css',
        'assets/css/tokens.css',
        'assets/css/reset.css',
        'assets/css/base.css',
        'assets/css/typography.css',
        'assets/css/layout.css',
        'assets/css/components/navigation.css',
        'assets/css/components/mega-menu.css',
        'assets/css/components/hero.css',
        'assets/css/components/buttons.css',
        'assets/css/components/forms.css',
        'assets/css/components/cards.css',
        'assets/css/components/sidebar.css',
        'assets/css/components/footer.css',
        'assets/css/components/pagination.css',
        'assets/css/components/toc.css',
        'assets/css/themes/dark.css',
        'assets/css/themes/motion.css',
        'assets/css/utilities.css',
    );

    $page_css_modules = array();

    if (is_front_page() || is_home()) {
        $page_css_modules[] = 'assets/css/pages/home.css';
    }

    if (is_page(array('tutorials', 'articles', 'guides', 'resources'))) {
        $page_css_modules[] = 'assets/css/pages/tutorials.css';
    }

    if (is_page('articles')) {
        $page_css_modules[] = 'assets/css/pages/articles.css';
    }

    if (is_page('guides')) {
        $page_css_modules[] = 'assets/css/pages/guides.css';
    }

    if (is_page('resources')) {
        $page_css_modules[] = 'assets/css/pages/resources.css';
    }

    if (is_singular('post')) {
        $page_css_modules[] = 'assets/css/pages/single.css';
    }

    if (is_page('about')) {
        $page_css_modules[] = 'assets/css/pages/about.css';
    }

    if (is_page('contact')) {
        $page_css_modules[] = 'assets/css/pages/contact.css';
    }

    $css_modules = array_merge($global_css_modules, $page_css_modules);

    $previous_style_handle = 'syntaxsidekick-child-style';

    foreach ($css_modules as $css_relative_path) {
        $style_handle = 'syntaxsidekick-' . sanitize_key(str_replace(array('/', '.css'), array('-', ''), $css_relative_path));

        wp_enqueue_style(
            $style_handle,
            get_stylesheet_directory_uri() . '/' . $css_relative_path,
            array($previous_style_handle),
            syntaxsidekick_get_asset_version($css_relative_path)
        );

        $previous_style_handle = $style_handle;
    }

    $nav_script_ver = syntaxsidekick_get_asset_version('assets/js/mega-menu.js');

    wp_enqueue_script(
        'syntaxsidekick-mega-menu',
        get_stylesheet_directory_uri() . '/assets/js/mega-menu.js',
        array(),
        $nav_script_ver,
        true
    );
    wp_script_add_data('syntaxsidekick-mega-menu', 'strategy', 'defer');

    wp_enqueue_script(
        'syntaxsidekick-theme-toggle',
        get_stylesheet_directory_uri() . '/assets/js/theme-toggle.js',
        array(),
        syntaxsidekick_get_asset_version('assets/js/theme-toggle.js'),
        true
    );
    wp_script_add_data('syntaxsidekick-theme-toggle', 'strategy', 'defer');

    if (function_exists('syntaxsidekick_get_mega_menu_js_payload')) {
        $payload = syntaxsidekick_get_mega_menu_js_payload();
        if (is_array($payload)) {
            wp_add_inline_script(
                'syntaxsidekick-mega-menu',
                'window.syntaxsidekickMegaMenuData = ' . wp_json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';',
                'before'
            );
        }
    }
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_child_enqueue_assets', 30);

/**
 * Detect whether current singular content uses block markup.
 *
 * @return bool
 */
function syntaxsidekick_current_view_uses_blocks() {
    if (! is_singular()) {
        return false;
    }

    $object = get_queried_object();
    if (! ($object instanceof WP_Post)) {
        return false;
    }

    return has_blocks((string) $object->post_content);
}

/**
 * Dequeue non-essential global assets where we provide custom equivalents.
 *
 * @return void
 */
function syntaxsidekick_optimize_frontend_assets() {
    if (is_admin()) {
        return;
    }

    wp_dequeue_script('wp-embed');
    wp_deregister_script('wp-embed');

    if (is_user_logged_in() || is_customize_preview() || syntaxsidekick_current_view_uses_blocks()) {
        return;
    }

    wp_dequeue_style('wp-block-library');
    wp_dequeue_style('wp-block-library-theme');
    wp_dequeue_style('classic-theme-styles');
    wp_dequeue_style('global-styles');
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_optimize_frontend_assets', 100);

/**
 * Remove dashicons for anonymous visitors.
 *
 * @return void
 */
function syntaxsidekick_dequeue_dashicons_for_guests() {
    if (is_admin() || is_user_logged_in()) {
        return;
    }

    wp_dequeue_style('dashicons');
}
add_action('wp_enqueue_scripts', 'syntaxsidekick_dequeue_dashicons_for_guests', 100);

/**
 * Restrict Easy TOC frontend assets to singular post pages.
 *
 * @return bool
 */
function syntaxsidekick_should_load_eztoc_assets() {
    return ! is_admin() && is_singular('post');
}

/**
 * Execute Easy TOC enqueue callbacks only when TOC is expected.
 *
 * @return void
 */
function syntaxsidekick_enqueue_eztoc_conditionally() {
    if (! syntaxsidekick_should_load_eztoc_assets() || ! class_exists('ezTOC')) {
        return;
    }

    ezTOC::enqueue_scripts();
    ezTOC::ez_toc_inline_styles();
    ezTOC::ez_toc_inline_sticky_styles();
    ezTOC::enqueue_scripts_for_exclude_css();
}

/**
 * Print Easy TOC schema only on supported single posts.
 *
 * @return void
 */
function syntaxsidekick_eztoc_schema_conditionally() {
    if (! syntaxsidekick_should_load_eztoc_assets() || ! class_exists('ezTOC')) {
        return;
    }

    ezTOC::ez_toc_schema_sitenav_creator();
}

/**
 * Rewire Easy TOC frontend hooks so they run only where needed.
 *
 * @return void
 */
function syntaxsidekick_optimize_toc_assets() {
    if (! class_exists('ezTOC')) {
        return;
    }

    remove_action('wp_enqueue_scripts', array('ezTOC', 'enqueue_scripts'));
    remove_action('wp_enqueue_scripts', array('ezTOC', 'ez_toc_inline_styles'));
    remove_action('wp_enqueue_scripts', array('ezTOC', 'ez_toc_inline_sticky_styles'));
    remove_action('wp_enqueue_scripts', array('ezTOC', 'enqueue_scripts_for_exclude_css'));
    remove_action('wp_head', array('ezTOC', 'ez_toc_schema_sitenav_creator'));

    add_action('wp_enqueue_scripts', 'syntaxsidekick_enqueue_eztoc_conditionally', 11);
    add_action('wp_head', 'syntaxsidekick_eztoc_schema_conditionally', 11);
}
add_action('init', 'syntaxsidekick_optimize_toc_assets', 20);

/**
 * Disable front-end assets/features we do not use.
 *
 * @return void
 */
function syntaxsidekick_optimize_frontend_bootstrap() {
    if (is_admin()) {
        return;
    }

    remove_action('wp_head', 'print_emoji_detection_script', 7);
    remove_action('wp_print_styles', 'print_emoji_styles');
    remove_action('wp_head', 'wp_oembed_add_discovery_links');
    remove_action('wp_head', 'wp_oembed_add_host_js');
    wp_dequeue_script('wp-embed');
}
add_action('init', 'syntaxsidekick_optimize_frontend_bootstrap');

/**
 * Apply lightweight iframe defaults for performance and accessibility.
 *
 * @param string $content Post content HTML.
 *
 * @return string
 */
function syntaxsidekick_optimize_content_iframes($content) {
    if (is_admin() || ! is_string($content) || '' === trim($content) || false === stripos($content, '<iframe')) {
        return $content;
    }

    if (! class_exists('DOMDocument')) {
        return $content;
    }

    $internal_errors = libxml_use_internal_errors(true);
    $document = new DOMDocument('1.0', 'UTF-8');
    $html = '<div id="ss-iframe-opt-root">' . mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8') . '</div>';

    if (! $document->loadHTML('<?xml encoding="utf-8" ?>' . $html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD)) {
        libxml_clear_errors();
        libxml_use_internal_errors($internal_errors);
        return $content;
    }

    $iframes = $document->getElementsByTagName('iframe');
    foreach ($iframes as $iframe) {
        if (! $iframe instanceof DOMElement) {
            continue;
        }

        if (! $iframe->hasAttribute('loading')) {
            $iframe->setAttribute('loading', 'lazy');
        }

        if (! $iframe->hasAttribute('referrerpolicy')) {
            $iframe->setAttribute('referrerpolicy', 'strict-origin-when-cross-origin');
        }

        if (! $iframe->hasAttribute('title')) {
            $iframe->setAttribute('title', __('Embedded content', 'syntaxsidekick-child'));
        }
    }

    $root = $document->getElementById('ss-iframe-opt-root');
    $output = '';
    if ($root instanceof DOMElement) {
        foreach ($root->childNodes as $child_node) {
            $output .= $document->saveHTML($child_node);
        }
    }

    libxml_clear_errors();
    libxml_use_internal_errors($internal_errors);

    return '' !== $output ? $output : $content;
}
add_filter('the_content', 'syntaxsidekick_optimize_content_iframes', 12);

/**
 * Apply persisted theme preference before first paint.
 *
 * @return void
 */
function syntaxsidekick_output_theme_bootstrap_script() {
    if (is_admin()) {
        return;
    }

    echo "<script>(function(){try{var d=document.documentElement;var k='syntaxsidekick-theme';var l='ss-theme';var t=localStorage.getItem(k);if(t!=='dark'&&t!=='light'){var legacy=localStorage.getItem(l);if(legacy==='dark'||legacy==='light'){t=legacy;localStorage.setItem(k,legacy);}else{t=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}}d.setAttribute('data-theme',t);}catch(e){if(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches){document.documentElement.setAttribute('data-theme','dark');}else{document.documentElement.setAttribute('data-theme','light');}}})();</script>\n";
}
add_action('wp_head', 'syntaxsidekick_output_theme_bootstrap_script', 1);

/**
 * Remove jQuery Migrate from frontend payload while keeping jQuery.
 *
 * @param WP_Scripts $scripts Scripts registry.
 *
 * @return void
 */
function syntaxsidekick_remove_jquery_migrate($scripts) {
    if (is_admin() || ! ($scripts instanceof WP_Scripts)) {
        return;
    }

    if (! isset($scripts->registered['jquery']) || ! is_array($scripts->registered['jquery']->deps)) {
        return;
    }

    $scripts->registered['jquery']->deps = array_values(
        array_diff($scripts->registered['jquery']->deps, array('jquery-migrate'))
    );
}
add_action('wp_default_scripts', 'syntaxsidekick_remove_jquery_migrate');

function syntaxsidekick_excerpt_length($length) {
    return 22;
}
add_filter('excerpt_length', 'syntaxsidekick_excerpt_length');

function syntaxsidekick_excerpt_more($more) {
    return '...';
}
add_filter('excerpt_more', 'syntaxsidekick_excerpt_more');

/**
 * Return local SVG icon markup by name.
 *
 * @param string $icon_name Icon filename without extension.
 * @param array  $args      Optional render args.
 *
 * @return string
 */
function syntaxsidekick_icon($icon_name, $args = array()) {
    static $raw_cache = array();

    $icon_name = sanitize_key((string) $icon_name);
    if ('' === $icon_name) {
        return '';
    }

    if (! array_key_exists($icon_name, $raw_cache)) {
        $icons_dir = trailingslashit(get_stylesheet_directory()) . 'assets/icons/';
        $path = $icons_dir . $icon_name . '.svg';

        if (! file_exists($path) || ! is_readable($path)) {
            $raw_cache[$icon_name] = '';
        } else {
            $raw = file_get_contents($path);
            if (false === $raw || '' === trim($raw)) {
                $raw_cache[$icon_name] = '';
            } else {
                $raw = preg_replace('/<\?xml[^>]*>\s*/i', '', $raw);
                $raw = is_string($raw) ? preg_replace('/<title>.*?<\/title>/is', '', $raw) : '';
                $raw = is_string($raw) ? trim($raw) : '';
                $raw_cache[$icon_name] = $raw;
            }
        }
    }

    $svg = $raw_cache[$icon_name];
    if (! is_string($svg) || '' === $svg) {
        return '';
    }

    $defaults = array(
        'class' => 'ss-menu-icon ss-icon--neutral',
        'decorative' => true,
        'title' => '',
        'label' => '',
    );

    $args = wp_parse_args(is_array($args) ? $args : array(), $defaults);
    $class_attr = trim((string) $args['class']);
    $decorative = (bool) $args['decorative'];
    $title = trim((string) $args['title']);
    $label = trim((string) $args['label']);

    if (false === stripos($svg, 'viewBox=')) {
        $svg = preg_replace('/<svg\b/i', '<svg viewBox="0 0 24 24"', $svg, 1);
        if (! is_string($svg)) {
            return '';
        }
    }

    $attrs = array();
    if ('' !== $class_attr) {
        $attrs[] = 'class="' . esc_attr($class_attr) . '"';
    }

    if ($decorative) {
        $attrs[] = 'aria-hidden="true"';
        $attrs[] = 'focusable="false"';
    } else {
        $attrs[] = 'role="img"';

        if ('' !== $label) {
            $attrs[] = 'aria-label="' . esc_attr($label) . '"';
        }

        if ('' !== $title && '' === $label) {
            $attrs[] = 'aria-label="' . esc_attr($title) . '"';
        }
    }

    $svg = preg_replace('/<svg\b([^>]*)>/i', '<svg$1 ' . implode(' ', $attrs) . '>', $svg, 1);
    if (! is_string($svg) || '' === trim($svg)) {
        return '';
    }

    if (! $decorative && '' !== $title) {
        $svg = preg_replace('/<svg\b[^>]*>/i', '$0<title>' . esc_html($title) . '</title>', $svg, 1);
        if (! is_string($svg)) {
            return '';
        }
    }

    return $svg;
}

/**
 * Get semantic icon color utility class by slug.
 *
 * @param string $slug Icon/topic slug.
 *
 * @return string
 */
function syntaxsidekick_get_icon_color_class($slug) {
    $slug = sanitize_key((string) $slug);

    $map = array(
        'html' => 'ss-icon--html5',
        'html5' => 'ss-icon--html5',
        'css' => 'ss-icon--css',
        'javascript' => 'ss-icon--javascript',
        'js' => 'ss-icon--javascript',
        'typescript' => 'ss-icon--typescript',
        'ts' => 'ss-icon--typescript',
        'react' => 'ss-icon--react',
        'vue' => 'ss-icon--vue',
        'vuejs' => 'ss-icon--vue',
        'wordpress' => 'ss-icon--wordpress',
        'accessibility' => 'ss-icon--accessibility',
        'performance' => 'ss-icon--performance',
    );

    return $map[$slug] ?? 'ss-icon--neutral';
}

function syntaxsidekick_fallback_menu($args = array()) {
    $menu_class = ! empty($args['menu_class']) ? (string) $args['menu_class'] : 'ss-nav-list ss-nav-list--fallback';

    $links = array(
        array(
            'label' => 'Home',
            'url' => home_url('/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('home'),
        ),
        array(
            'label' => 'Articles',
            'url' => home_url('/articles/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('articles'),
        ),
        array(
            'label' => 'Tutorials',
            'url' => home_url('/tutorials/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('tutorials'),
        ),
        array(
            'label' => 'Guides',
            'url' => home_url('/guides/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('guides'),
        ),
        array(
            'label' => 'Resources',
            'url' => home_url('/resources/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('resources'),
        ),
        array(
            'label' => 'About',
            'url' => home_url('/about/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('about'),
        ),
        array(
            'label' => 'Contact',
            'url' => home_url('/contact/'),
            'active' => syntaxsidekick_is_mega_menu_section_active('contact'),
        ),
    );

    echo '<ul class="' . esc_attr($menu_class) . '" role="list">';

    foreach ($links as $link) {
        $item_classes = 'ss-nav-item';
        $link_classes = 'ss-nav-link';
        $section_key = syntaxsidekick_nav_section_from_url($link['url']);
        $data_key_attr = '' !== $section_key ? ' data-ss-menu-key="' . esc_attr($section_key) . '"' : '';

        if ($link['active']) {
            $item_classes .= ' current-menu-item is-active';
            $link_classes .= ' is-active';
        }

        echo '<li class="' . esc_attr($item_classes) . '"><a class="' . esc_attr($link_classes) . '" href="' . esc_url($link['url']) . '"' . $data_key_attr . '>' . esc_html($link['label']) . '</a></li>';
    }

    echo '</ul>';
}

/**
 * Normalize request path relative to site home path.
 *
 * @return string
 */
function syntaxsidekick_get_relative_request_path() {
    $request_uri = isset($_SERVER['REQUEST_URI']) ? wp_unslash((string) $_SERVER['REQUEST_URI']) : '/';
    $request_path = wp_parse_url($request_uri, PHP_URL_PATH);
    $request_path = is_string($request_path) && '' !== $request_path ? $request_path : '/';

    $home_path = wp_parse_url(home_url('/'), PHP_URL_PATH);
    $home_path = is_string($home_path) && '' !== $home_path ? $home_path : '/';

    $request_path = '/' . ltrim($request_path, '/');

    if ('/' !== $home_path) {
        $trimmed_home = rtrim($home_path, '/');
        if ($request_path === $trimmed_home) {
            $request_path = '/';
        } elseif (0 === strpos($request_path, $trimmed_home . '/')) {
            $request_path = substr($request_path, strlen($trimmed_home));
            $request_path = '' === $request_path ? '/' : $request_path;
        }
    }

    if ('/' !== $request_path && '/' !== substr($request_path, -1)) {
        $request_path .= '/';
    }

    return $request_path;
}

/**
 * Map navigation URL to its section key.
 *
 * @param string $url Menu URL.
 *
 * @return string
 */
function syntaxsidekick_nav_section_from_url($url) {
    $path = wp_parse_url((string) $url, PHP_URL_PATH);
    $path = is_string($path) && '' !== $path ? $path : '/';

    $home_path = wp_parse_url(home_url('/'), PHP_URL_PATH);
    $home_path = is_string($home_path) && '' !== $home_path ? $home_path : '/';

    $path = '/' . ltrim($path, '/');

    if ('/' !== $home_path) {
        $trimmed_home = rtrim($home_path, '/');
        if ($path === $trimmed_home) {
            $path = '/';
        } elseif (0 === strpos($path, $trimmed_home . '/')) {
            $path = substr($path, strlen($trimmed_home));
            $path = '' === $path ? '/' : $path;
        }
    }

    if ('/' !== $path && '/' !== substr($path, -1)) {
        $path .= '/';
    }

    $section_map = array(
        '/' => 'home',
        '/articles/' => 'articles',
        '/tutorials/' => 'tutorials',
        '/guides/' => 'guides',
        '/resources/' => 'resources',
        '/about/' => 'about',
        '/contact/' => 'contact',
    );

    return isset($section_map[$path]) ? $section_map[$path] : '';
}

function syntaxsidekick_primary_nav_item_classes($classes, $menu_item, $args) {
    if (empty($args->theme_location) || 'primary' !== $args->theme_location) {
        return $classes;
    }

    $classes[] = 'ss-nav-item';

    $section_key = syntaxsidekick_nav_section_from_url(isset($menu_item->url) ? (string) $menu_item->url : '');

    $classes = array_values(
        array_filter(
            $classes,
            static function ($class_name) {
                return ! in_array($class_name, array('is-active', 'current-menu-item', 'current-menu-parent', 'current-menu-ancestor'), true);
            }
        )
    );

    if ('' !== $section_key && syntaxsidekick_is_mega_menu_section_active($section_key)) {
        $classes[] = 'is-active';
        $classes[] = 'current-menu-item';
    }

    return array_values(array_unique($classes));
}
add_filter('nav_menu_css_class', 'syntaxsidekick_primary_nav_item_classes', 10, 3);

function syntaxsidekick_primary_nav_link_attributes($atts, $menu_item, $args) {
    if (empty($args->theme_location) || 'primary' !== $args->theme_location) {
        return $atts;
    }

    $classes   = isset($atts['class']) ? (string) $atts['class'] : '';
    $class_arr = preg_split('/\s+/', trim($classes));
    $class_arr = is_array($class_arr) ? array_filter($class_arr) : array();
    $class_arr[] = 'ss-nav-link';

    $section_key = syntaxsidekick_nav_section_from_url(isset($menu_item->url) ? (string) $menu_item->url : '');
    if ('' !== $section_key && syntaxsidekick_is_mega_menu_section_active($section_key)) {
        $class_arr[] = 'is-active';
    }

    if ('' !== $section_key) {
        $atts['data-ss-menu-key'] = $section_key;
    }

    $atts['class'] = implode(' ', array_values(array_unique($class_arr)));

    return $atts;
}
add_filter('nav_menu_link_attributes', 'syntaxsidekick_primary_nav_link_attributes', 10, 3);

function syntaxsidekick_has_seo_plugin() {
    return defined('RANK_MATH_VERSION') || defined('WPSEO_VERSION') || defined('AIOSEO_VERSION') || defined('SEOPRESS_VERSION');
}

function syntaxsidekick_fallback_meta_description() {
    if (is_front_page() || is_home()) {
        return get_bloginfo('description');
    }

    if (is_singular()) {
        $description = trim((string) get_the_excerpt());
        if ('' === $description) {
            $description = wp_strip_all_tags((string) get_the_content());
        }

        return wp_trim_words($description, 28, '...');
    }

    if (is_archive()) {
        $description = trim((string) get_the_archive_description());
        if ('' !== $description) {
            return wp_strip_all_tags($description);
        }
    }

    return get_bloginfo('description');
}

function syntaxsidekick_output_fallback_seo_meta() {
    if (syntaxsidekick_has_seo_plugin()) {
        return;
    }

    $description = syntaxsidekick_fallback_meta_description();
    if ('' !== $description) {
        echo '<meta name="description" content="' . esc_attr($description) . '">' . "\n";
    }

    $canonical = wp_get_canonical_url();
    if (! $canonical) {
        $canonical = is_home() ? home_url('/') : get_permalink();
    }

    if ($canonical) {
        echo '<link rel="canonical" href="' . esc_url($canonical) . '">' . "\n";
    }

    if (is_single()) {
        $schema = array(
            '@context' => 'https://schema.org',
            '@type' => 'Article',
            'headline' => get_the_title(),
            'datePublished' => get_the_date('c'),
            'dateModified' => get_the_modified_date('c'),
            'author' => array(
                '@type' => 'Person',
                'name' => get_the_author(),
            ),
            'mainEntityOfPage' => array(
                '@type' => 'WebPage',
                '@id' => get_permalink(),
            ),
        );

        if (has_post_thumbnail()) {
            $image_url = get_the_post_thumbnail_url(null, 'large');
            if ($image_url) {
                $schema['image'] = array($image_url);
            }
        }

        echo '<script type="application/ld+json">' . wp_json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>' . "\n";
    }
}
add_action('wp_head', 'syntaxsidekick_output_fallback_seo_meta', 5);

function syntaxsidekick_get_post_read_time($post_id) {
    $post_id = (int) $post_id;
    if ($post_id <= 0) {
        return '1 min read';
    }

    $word_count = str_word_count(wp_strip_all_tags((string) get_post_field('post_content', $post_id)));
    $minutes    = max(1, (int) ceil($word_count / 200));

    return $minutes . ' min read';
}

function syntaxsidekick_get_home_feature_highlights() {
    return array(
        array(
            'icon' => '</>',
            'title' => 'Modern Standards',
            'description' => 'CSS, JS, TS and beyond',
        ),
        array(
            'icon' => 'A11y',
            'title' => 'Accessibility First',
            'description' => 'Inclusive by default',
        ),
        array(
            'icon' => 'Perf',
            'title' => 'Performance Focused',
            'description' => 'Fast by design',
        ),
        array(
            'icon' => 'Idea',
            'title' => 'Practical Learning',
            'description' => 'Real world examples',
        ),
    );
}

function syntaxsidekick_get_live_video_data() {
    $default = array(
        'state' => 'live',
        'title' => 'Live on Twitch',
        'description' => 'Building a responsive dashboard with CSS Grid and Container Queries.',
        'platform' => 'Twitch',
        'cta_label' => 'Watch Live',
        'cta_url' => 'https://www.twitch.tv/',
        'latest_title' => 'CSS Container Queries: Full Guide',
        'latest_url' => 'https://www.youtube.com/',
        'latest_duration' => '18:42',
        'latest_thumbnail' => '',
        'latest_thumbnail_alt' => 'Latest video thumbnail',
        // Reserved for future integrations.
        'providers' => array('twitch', 'youtube_live', 'youtube_latest'),
        'provider_priority' => array('twitch', 'youtube_live', 'youtube_latest'),
    );

    return apply_filters('syntaxsidekick_live_video_data', $default);
}
